### ISSUE TITLE
Find resulting non-object

### ISSUE THREAD

**Issue by AgentGeek** [monkeysuffrage/advanced_html_dom#12]
Well i tried to migrate my code that uses simple_html_dom parser but when using find it results in error, trying to get property of non-object.

The code is simple and worked fine with simple_html_dom

here is the code.

`$page = file_get_html('https://example.com/somepage.html');`
`$code = $page->find('div["class=header"]', 0)->plaintext;`
`echo $code;`

I don't know why it keeps resulting this maybe its because the attribute i need have more then one class though it still contain header in it.

**Comment by monkeysuffrage** [comment]
That css is wrong. Try div[class="header"], div[class=header] or div.header

**Comment by AgentGeek** [comment]
Sorry mistakenly entered that quote so i tried all of them and third one worked fine, now i am migrating the full code using the third one. Thanks keep it up.
