### ISSUE TITLE
two classes selected not as intended

### ISSUE THREAD

**Issue by Areso** [monkeysuffrage/advanced_html_dom#15]
```
<?php
require('advanced_html_dom.php');

// Create DOM from URL or file
$html = file_get_html('http://taranko-shop.ru/1700/');
echo isset ($html)."<br>";

$i = 1;
foreach ($html->find('.image.selected', 0) as $image) {
        echo 'partial success';
}

//var_dump($myvar);
?>


```
this code returns 4 matches in attached file, though should found only one.
[htmltoparse.html.txt](https://github.com/monkeysuffrage/advanced_html_dom/files/1838207/htmltoparse.html.txt)

**Comment by monkeysuffrage** [comment]
You want to leave out the `,0` - otherwise you will get a single node.
