### ISSUE TITLE
404 and other error codes from HTTP server and service pages

### ISSUE THREAD

**Issue by Areso** [monkeysuffrage/advanced_html_dom#16]
Could you kindly add to description, how to handle work with 404 codes and so on? If open the page in question in browser, there is some CMS page with 404 description, not a barebone 404 http code.

For example right now I got
$html_text2      = file_get_contents(page_url);// OR die('not found'); 
$html =  str_get_html($html_text2);
OR
$html_text2      = file_get_html(page_url);// OR die('not found'); 

Warning: file_get_contents(http://taranko-shop.ru/1000): failed to open stream: HTTP request failed! 
HTTP/1.1 404 Not Found in /var/www/html/index.php on line 22
Fatal error: Call to a member function saveHTML() on a non-object in /var/www/html/vendor/advanced_html_dom.php on line 32

Warning: file_get_contents(http://taranko-shop.ru/1000): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /var/www/html/index.php on line 22

Right now I use the following code
if (gettype($html_text2) === 'boolean') {
	$error=1;
}
but I think there is may be a better solution, rather my workaround,

It would be wonderful to get error HTML pages served by HTTP server as objects, or, at least, string with HTTP headers.

**Comment by monkeysuffrage** [comment]
This is a core PHP thing so I'm not going to address it here. I think the idiomatic way to deal with it is probably:
`$str = file_get_contents($url) or die('bad response!');`
Also, use curl for response status codes.

**Comment by Areso** [comment]
Well, I cannot send my script to die, because there is about 1000 pages it should grab in cycle, it should not stopped if some of them 404 (and some of them are, indeed, and that is OK).
Of course, I can use cURL, as you suggest. But it still looks like a workaround, though it better from logic point of view. 
Why it still looks like a workaround? Because for each page I should do at least 2 connection (check headers and then download, if it's 200), each connection is about 1s. 
1000 pages will be worked out not it 1000s as it has now, but in 2000s (that a quite different).
There is modificated Simple HTML DOM Parser with such check in attachment, may be you could bring the functionality from the library? Consider it as feature request.
[simple_html_dom.zip](https://github.com/monkeysuffrage/advanced_html_dom/files/1845093/simple_html_dom.zip)

**Comment by monkeysuffrage** [comment]
I'll consider it if you make a pull request but it doesn't sound like
something that belongs here.
