### ISSUE TITLE
Php7 error when creating new instance of AdvancedHtmlDom

### ISSUE THREAD

**Issue by aayaresko** [monkeysuffrage/advanced_html_dom#2]
On php 7 code stops on the creation of new instance of AdvancedHtmlDom with some of this errors:
`*** Error in 'php': corrupted double-linked list: 0x0000000001de0020 ***`
`*** Error in 'php': malloc(): smallbin double linked list corrupted: 0x00000000022a1cb0 ***`
`*** Error in 'php': free(): invalid pointer: 0x00007f906a4a0624 ***`
Is this php 7 problem or AdvancedHtmlDom is incompatible with php7 at all?

PHP Version => 7.0.4-1~dotdeb+8.1
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux

**Comment by aayaresko** [comment]
Further study has led me to the line 173 of AdvancedHtmlDom.php.
In this line code stops with errors.

**Comment by monkeysuffrage** [comment]
I've never tested with PHP 7, but I'm surprised to see memory errors. Is that an official PHP version?

**Comment by aayaresko** [comment]
PHP sources are taken from [here](https://www.dotdeb.org/2016/03/04/php-7-0-4-for-jessie/)
AFAIK they simply made a debian repository using [this](http://php.net/archive/2016.php#id2016-03-03-1) version.

Forther study has led me to line 603, where preg_split is made with this huge expression.

**Comment by aayaresko** [comment]
running in php cli this code
`preg_split('/(:(?:nth-last-child|nth-of-type|nth-last-of-type|first-child|last-child|first-of-type|last-of-type|only-child|only-of-type|nth-child|first|last|gt|lt|eq|root|nth|empty|not|has|contains|parent|link|visited|hover|active)(?:\((?>[^()]|(?R))*\))?|\[(?>[^\[\]]|(?R))*\]|[#.][\w-]+)/', 'body', 0, PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY)`
leads to an error:
*** Error in `php': free(): invalid pointer: 0x00007f906a4a0624 ***

**Comment by monkeysuffrage** [comment]
It could be changes in the PHP 7 regex engine causing this, I have no knowledge of what changes were made though.

**Comment by aayaresko** [comment]
looks loke it is a regex engine problem...
`preg_match('/(:(?:nth-last-child|nth-of-type|nth-last-of-type|first-child|last-child|first-of-type|last-of-type|only-child|only-of-type|nth-child|first|last|gt|lt|eq|root|nth|empty|not|has|contains|parent|link|visited|hover|active)(?:\((?>[^()]|(?R))*\))?|\[(?>[^\[\]]|(?R))*\]|[#.][\w-]+)/', '#hello-world')`
fails with error

**Comment by monkeysuffrage** [comment]
I tested it with PHP7.0.4 and 7.0.5 [here](http://sandbox.onlinephpfunctions.com/code/fd89a11b1c2ed2af5a8c4916ab1ad9f2707941fe)

I'm not seeing any issue so I'm closing this one.

**Comment by macjohnny** [comment]
This seems to occur only in rare cases and might be related to:
https://bugs.php.net/bug.php?id=71937&edit=1
we also have the same issue with a different php software (TYPO3) which only occurs on a specific hosting system with Debian 8.5+PHP 7.0.8, but does not occur on other systems (Ubuntu14+PHP7.0.6, Mac OS X 10.11.4+PHP7.0.0, Mac OS X 10.11.4+PHP7.0.8), so it seems to depend on the configuration/hosting environment

**Comment by macjohnny** [comment]
we could track down the problem to the version of the pcre extension.

on the system where the issue occurs, we have PCRE Library Version 8.35 2014-04-04
on the system where it works, we have PCRE Library Version 8.38 2015-11-23

So updating the PCRE Library Version by updating the PHP version should fix the problem. However on our system with Debian + PHP7.0.7 the PCRE Library Version should already be 8.38, but actually is 8.35, so it might not have been included in the debian package.

See also 

https://bugs.php.net/bug.php?id=71659
https://github.com/gplessis/dotdeb-php/issues/124
https://bugs.exim.org/show_bug.cgi?id=1803

A quick-fix if you cannot update: set the following php.ini setting:

pcre.jit = 0

**Comment by monkeysuffrage** [comment]
Thanks @macjohnny,
I'm not sure what to make of this. It sounds like the pcre issue is resolved going forward but may still be out there in the wild so hopefully that's the last we hear from this.

**Comment by macjohnny** [comment]
@monkeysuffrage I would leave this issue closed, since this is not directly related to monkeysuffrage. Moreover, setups with PHP7 should be updated anyway.
