### ISSUE TITLE
PHP 7.0.12 issues

### ISSUE THREAD

**Issue by andrei-jurescu** [monkeysuffrage/advanced_html_dom#5]
Hi.

I was running PHP 5.6 before, and your code runs perfect.
But now, I have upgraded to PHP 7.0.12, and I don't get all the data as before. Instead, I see a few warnings and some notices like this:

PHP Notice:  Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295
PHP Warning:  Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145

Warning: Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145
PHP Notice:  Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295
PHP Notice:  Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295
PHP Warning:  Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145

Warning: Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145
PHP Notice:  Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295
PHP Notice:  Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295
PHP Warning:  Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145

Warning: Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145
PHP Notice:  Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295
PHP Notice:  Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295
PHP Warning:  Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145

Warning: Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145
PHP Notice:  Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295
PHP Notice:  Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Array to string conversion in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295
PHP Warning:  Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145

Warning: Unknown method or property: array in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 145
PHP Notice:  Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

Notice: Uninitialized string offset: 1 in /Applications/MAMP/htdocs/scrap-v2/client/pgbrowser/advanced_html_dom.php on line 295

As you can see, I'm using pgbrowser too (https://github.com/monkeysuffrage/pgbrowser)

Any help with this please? It would be much appreciated. Thank you!

**Comment by monkeysuffrage** [comment]
Hi Andrei,
Can you provide a test case?
Thanks.

**Comment by andrei-jurescu** [comment]
Hi,

Thank you for you quick response.

I’ve attached the source code I’m using.
Just unzip, and from terminal, cd to ‘client_PHP7.0.12’ folder, and then run “php klikimobiliare.ro.php” using php 7.0.12.

Thank you. 
Andrei

**Comment by monkeysuffrage** [comment]
Hi Andrei,
I fixed the problem but I need to find a way to undo the last merge before
I push it. If anybody can talk me through that I will appreciate it.

**Comment by andrei-jurescu** [comment]
Hi, that's great!
To undo the last merge maybe you can try to reset HEAD to some older commit, or REBASE.

**Comment by monkeysuffrage** [comment]
Ok, I managed to push the latest fixes, this should resolve the php 7 issues.

**Comment by andrei-jurescu** [comment]
Thank you. It works great, no more issues. Just to let you know, I think you let by mistake an unresolved conflict in advanced_html_dom.php file, line 108.
I will close this issue, as you fixed it. Thanks again. Have a great weekend!

**Comment by monkeysuffrage** [comment]
No, the new fixes should address that one too.
Thanks.
