### ISSUE TITLE
Corrupts international characters in iso-8859-1

### ISSUE THREAD

**Issue by chrisjj** [monkeysuffrage/advanced_html_dom#6]
This 

```
include 'simple_html_dom.php';
print(str_get_html("á")->innertext );
```
outputs á as expected. http://i.imgur.com/oAwouWT.png

But 

```
include 'advanced_html_dom.php';
print(str_get_html("á")->innertext );
```

outputs Ã¡ as not expected. http://i.imgur.com/n59JToR.png

It looks to me that Advanced HTML DOM is messing up on character encoding.

The same corruption shows on a validated HTML document: 

```
include 'advanced_html_dom.php';
print(str_get_html('
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE></TITLE>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</HEAD><BODY><P>á</P></BODY></HTML>
')->innertext);

```

(Validation here: http://i.imgur.com/RemHW4e.png , http://i.imgur.com/VT3wwwY.png .)

Here's an example of the effect in production:

With simple_html_dom:
![image](https://cloud.githubusercontent.com/assets/6157073/19911767/9350d076-a08d-11e6-9ffb-1fc5a38cb68f.png)

With advanced_html_dom:
![image](https://cloud.githubusercontent.com/assets/6157073/19911762/89f24550-a08d-11e6-81e2-bbcefda96234.png)

This could be a problem to anyone relying on advanced_html_dom's "[_The goal of this project is to be a DOM-based drop-in replacement for PHP's simple html dom library ... If you use file/str_get_html then you don't need to change anything._](https://archive.is/QtSuj#selection-933.34-933.100)".

Workarounds: 
* recode the source to be Unicode e.g. UTF-8.
* convert the output back using e.g. mb_convert_encoding($o, /*to*/ "ISO-8859-1",/*from*/ "UTF-8")

**Comment by monkeysuffrage** [comment]
Maybe it expects the encoding in the dtd? Anyway that's not html so I don't
really consider this an issue.

**Comment by chrisjj** [comment]
> Maybe it expects the encoding in the dtd?

HTML provides no way to specify encoding in the DTD.

> Anyway that's not html so I don't really consider this an issue.

It's HTML enough for simple_html_dom so it should be HTML enough for this "drop-in replacement" advanced_html_dom .

Plus the same fail appears on:

```
include 'advanced_html_dom.php';
print(str_get_html('
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE></TITLE>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</HEAD><BODY><P>á</P></BODY></HTML>
')->innertext);

```

**Comment by monkeysuffrage** [comment]
This library is DomDocument based so it will do things like that. I think
this is actually proper behaviour for that encoding (iso-8859-1)

**Comment by chrisjj** [comment]
>  I think this is actually proper behaviour for that encoding (iso-8859-1)

The fact this module advertises itself as a drop-in replacement for a module that doesn't do this makes this behaviour improper.

Regardless, changing the encoding without being requested is not proper.

**Comment by monkeysuffrage** [comment]
It's happening because the dtd charset doesn't match your encoding. Again,
this is DomDocument doing this, not this library.

**Comment by chrisjj** [comment]
> It's happening because the dtd charset doesn't match your encoding.

There's no such thing as a DTD charset.  DTD defines types and structure, not charset.

And even if I add charset spec in META, the fail persists http://i.imgur.com/cjLA0ux.png

> Again, this is DomDocument doing this, not this library.

I'm not using DomDocument. I'm using Advanced HTML DOM, which claims "you don't need to change anything" and yet if I don't change anything, it messes up my character encoding.

Can you post an example with ANSI input that does NOT get messed-up like this?

**Comment by monkeysuffrage** [comment]
What's the encoding of the file in that screenshot? If it's utf8 then it's
behaving properly. Otherwise it's not but I can't reproduce it on mine.
Maybe you're using an old PHP.

**Comment by chrisjj** [comment]
> What's the encoding of the file in that screenshot? If it's utf8 then it's
behaving properly. 

It is Windows-1252. As the charset= says.

> Otherwise it's not

Thanks.

>  but I can't reproduce it on mine. Maybe you're using an old PHP.

5.6.13 on Windows. What's yours?

**Comment by monkeysuffrage** [comment]
7.0.9 on Windows. If nothing is keeping you from moving to PHP 7, I
recommend it. Otherwise maybe it makes sense to keep using simple-html-dom
for your project.

**Comment by chrisjj** [comment]
> 7.0.9 on Windows.

Thanks for the info,

You wrote "I tested this library with php 7.0.1 - 7.0.5 as well as PHP 5.3 and up, everything seems to be working."  https://archive.is/qR0vJ . Have you done a 5.3 test of iso-8859-1  or Windows-1282 or any other 8-bit charset beyond ASCII ?

**Comment by monkeysuffrage** [comment]
No, and I don't plan to because DomDocument issues are beyond the scope of
this project.

**Comment by chrisjj** [comment]
Then you should probably remedy this misrep of yours: "If you use file/str_get_html then you don't need to change anything" https://github.com/monkeysuffrage/advanced_html_dom

**Comment by monkeysuffrage** [comment]
I feel like it's covered in the "What's different" section but if you want
to amend that feel free.

**Comment by chrisjj** [comment]
I don't think "What's different" _Mostly just formatting (spaces) in the html._ or anything else there covers this corruption of international characters.

**Comment by monkeysuffrage** [comment]
So fork it, make some changes, and submit a pull request.
