### ISSUE TITLE
Converts html character entities to UTF-8

### ISSUE THREAD

**Issue by chrisjj** [monkeysuffrage/advanced_html_dom#8]
This code in [Windows-1252](http://i.imgur.com/8AzRGmp.png) encoding

```
<?php
include 'advanced_html_dom.php';
print(str_get_html('<body><p>&bull; and &#xE9;</p></body>')->innertext );
```

is expected to output 

      `<body><p>&bull; and &#xE9;</p></body>`

but outputs

      `<body><p>â€¢ and Ã©</p></body>` http://i.imgur.com/fI6XxVU.png

i.e. it is converting html character entity references and numeric character references to UTF-8 characters.

This could be a problem to anyone relying on advanced_html_dom's "[_The goal of this project is to be a DOM-based drop-in replacement for PHP's simple html dom library ... If you use file/str_get_html then you don't need to change anything._](https://archive.is/QtSuj#selection-933.34-933.100)".

**Comment by MickBenjamins** [comment]
Would love it if anyone has a solution to this, as I am currently encountering this.

**Comment by monkeysuffrage** [comment]
It looks like you want html instead of innertext.

**Comment by MickBenjamins** [comment]
Im using:

`$videoTitle = $html->find('[property="og:title"]', 0);
$videoTitle = $videoTitle->content;`

To grab the title of a YouTube video. Works as expected with simple_html_dom, but in advanced_html_dom I get weird characters.

Any idea?

**Comment by monkeysuffrage** [comment]
What video?

**Comment by MickBenjamins** [comment]
This one for example: https://www.youtube.com/watch?v=9AeLoMqt4Dk

**Comment by monkeysuffrage** [comment]
That's happening because the page doesn't declare utf8 charset:
<meta charset="UTF-8">
You would need to inject that into the html or fix it with regex.

**Comment by MickBenjamins** [comment]
Im trying to do that via:

`$html->find('head', 0)->innertext = '<meta charset="UTF-8">' . $html->find('head', 0)->innertext;`

Resulting in:
`// Create DOM from URL`
`$html = file_get_html($_POST['youtubelink']);`

`$html->find('head', 0)->innertext = '<meta charset="UTF-8">' . $html->find('head', 0)->innertext;`

`// Find video Title`

`$videoTitle = $html->find('[property="og:title"]', 0);`
`$videoTitle = $videoTitle->content;`

`// Print the value to the website`
`echo '<b>Title:</b> ' . $videoTitle . '<br>';`

But this doesnt work. Am I missing something totally obvious here?

**Comment by monkeysuffrage** [comment]
Yes, it has to be there when file_get_html() is called:
$str = str_replace('<head>', '<head><meta charset="UTF-8">',
file_get_contents($url));
$html = str_get_html($str);

**Comment by MickBenjamins** [comment]
monkeysuffrage, firstly: thanks for your help so far!
This is the struggle of a non-coder trying to get things to work ;-)

I slept on it, but still havent been able to figure it out. Currently I have:
```
$str = str_replace('<head>', '<head><meta charset="UTF-8">', file_get_html($_POST['youtubelink']));
$html = str_get_html($str);
```

The replacing works, I checked this by outputting the html as plain text via echo htmlspecialchars($YOUR_HTML);
But still I get the 'weird' character, do you have any other ideas?

**Comment by monkeysuffrage** [comment]
Are you using an old PHP maybe? Make sure you're using version 7+

**Comment by MickBenjamins** [comment]
I was at 5.6. Just tried with both 7.0 and 7.1 without any luck

**Comment by monkeysuffrage** [comment]
include 'advanced_html_dom.php';

$str = str_replace('<head>', '<head><meta charset="UTF-8">',
file_get_contents("https://www.youtube.com/watch?v=9AeLoMqt4Dk"));
$html = str_get_html($str);

$videoTitle = $html->find('[property="og:title"]', 0);

echo $videoTitle->content . "\n";

Works for me on 5.5 and 7+

**Comment by MickBenjamins** [comment]
I have no idea why, but that works perfectly. I have adopted this so instead of a fixed URL it takes the URL I input via POST. Still works, yay!

Thanks so much for helping out monkeysuffrage!
